# Generated by Django 5.0.3 on 2024-03-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workers", "0002_worker_is_admin_alter_worker_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="username",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
