# Generated by Django 5.0.3 on 2024-03-25 09:04

import django.contrib.auth.models
import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workers", "0003_alter_worker_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="worker",
            managers=[
                ("object", django.db.models.manager.Manager()),
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
