version: '3'
services:
  db:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_EXTENSIONS: uuid-ossp pgcrypto
    volumes:
      - db-data:/data/postgres

  api:
    build:
      context: .
      args:
        REQUIREMENTS_FILE: requirements.txt
    ports:
      - 8000:8000
    env_file: .env
    command: 'sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"'
    volumes:
      - ./:/app
    depends_on:
      - db

volumes:
  db-data: